name: lotto_mate
description: 로또메이트
publish_to: 'none'
version: 1.0.8+9

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0
  # share: ^2.0.1

  get: ^4.1.4
  provider: ^5.0.0

  sqflite: ^2.0.0+3
  path: ^1.8.0

  firebase_core: ^1.1.0
  cloud_firestore: ^1.0.7
  # firebase_messaging: ^9.1.3
  firebase_remote_config: ^0.10.0
  flutter_local_notifications: ^6.0.0

  google_mobile_ads: ^0.12.1+1
  flutter_coupang_ad:
    git:
      url: https://github.com/empering/flutter-coupang_ad

  convex_bottom_bar: ^3.0.0
  flutter_spinkit: ^5.0.0
  font_awesome_flutter: ^9.0.0
  animations: ^2.0.0
  search_choices: ^2.0.3
  percent_indicator: ^3.0.1
  double_back_to_close_app: ^2.0.1

  qrscan: ^0.3.1
  permission_handler: ^8.0.0+2
  package_info: ^2.0.0
  url_launcher: ^6.0.3
  share: ^2.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: CookieRun
      fonts:
        - asset: fonts/CookieRun Regular.otf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
